# Generated by Django 5.0.1 on 2024-01-11 18:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='probedata',
            options={'verbose_name': 'Probe Data', 'verbose_name_plural': 'Probe Data'},
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
