# Generated by Django 5.0.1 on 2024-01-13 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_probedata_read_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probedata',
            name='humidity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='probedata',
            name='light_level',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='probedata',
            name='soil_moisture',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='probedata',
            name='temperature',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-100.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddConstraint(
            model_name='plant',
            constraint=models.CheckConstraint(check=models.Q(('temperature_min__lte', models.F('temperature_max'))), name='temperature_min_lte_temperature_max'),
        ),
        migrations.AddConstraint(
            model_name='plant',
            constraint=models.CheckConstraint(check=models.Q(('in_sunlight_procent_min__lte', models.F('in_sunlight_procent_max'))), name='in_sunlight_procent_min_lte_in_sunlight_procent_max'),
        ),
        migrations.AddConstraint(
            model_name='plant',
            constraint=models.CheckConstraint(check=models.Q(('humidity_min__lte', models.F('humidity_max'))), name='humidity_min_lte_humidity_max'),
        ),
        migrations.AddConstraint(
            model_name='plant',
            constraint=models.CheckConstraint(check=models.Q(('soil_moisture_min__lte', models.F('soil_moisture_max'))), name='soil_moisture_min_lte_soil_moisture_max'),
        ),
    ]
