# Generated by Django 5.0.1 on 2024-01-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_alter_probe_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probe',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='probe',
            name='name',
            field=models.CharField(default='Probe', max_length=200),
        ),
    ]
